### ISSUE TITLE
Publish the role to galaxy

### ISSUE THREAD

**Issue by vkamlov** [rlex/ansible-role-k3s#1]
It'll be nice to publish your role to galaxy.ansible.com for more convenient usage.

**Comment by rlex** [comment]
tbh never got to it. Is it as easy as adding meta/defaults.yaml and pressing button in galaxy?

**Comment by vkamlov** [comment]
tbh idk. It's just a recommendation for the easiest download of the role.

**Comment by unixfox** [comment]
You don't necessarily need to put on galaxy, you can just add a meta/defaults.yaml like here: https://github.com/angristan/ansible-restic/blob/master/meta/main.yml
And people will be able to use it in their requirements.txt like this:
```yaml
---
- name: ansible-role-k3s
  src: https://github.com/rlex/ansible-role-k3s.git
  scm: git
```
